### ISSUE TITLE
AzureIoT simplesample_mqtt on ESP8266 - float issue

### ISSUE THREAD

**Issue by v-liujxu** [Azure/azure-iot-arduino-protocol-mqtt#10]
I tested simplesample_mqtt  on a generic ESP8266, even though not _SparkFun Thing_.  In the sample,  the parameters of _Temperature_ and _Humidity_ are defined as float type, but when i used device explorer to view the message, it is as below:

> {"DeviceId":"device1", "WindSpeed":12, "Temperature":**%.*f**, "Humidity":**%.*f**}

The values are wrong. I tracked the data of message sent from ESP8266 by adding the below code:

```
            (void)printf("destination: %s \r\n",destination); 
             sendMessage(iotHubClientHandle, destination, destinationSize, myWeather);
```

It seems that the macro _**SERIALIZE**_ cause the issue. Does this macro support float serializing on ESP8266?

**Comment by dilthings** [comment]
Adding the Microsoft Azure forum discussion on this as a reference for more information:

https://social.microsoft.com/Forums/azure/en-US/253b1f7e-d60d-40c1-877e-ce2519f0fcd1/azureiot-simplesamplemqtt-on-esp8266-float-issue?forum=azureiothub

**Comment by JetstreamRoySprowl** [comment]
This is due to a bug (or feature) in the Espressif's ESP8266 printf functionality. We are tracking this issue in our backlog, but do not yet have a schedule for fixing it.

**Comment by v-liujxu** [comment]
I think [ArduinoJson](https://github.com/bblanchon/ArduinoJson) can be instead to serialize the object data, it can serialize float type to json string.

**Comment by JetstreamRoySprowl** [comment]
The 2.4.0 version of [Arduino libraries for ESP8266](https://github.com/esp8266/Arduino) add printf support, and version 1.0.44 of the Azure IoT Arduino libraries work with it.
