### ISSUE TITLE
Linker issue relating to strftime?

### ISSUE THREAD

**Issue by onionhammer** [Azure/azure-iot-arduino-protocol-mqtt#11]
Using platformio, I receive the following error when I use AzureIoTProtocol_MQTT

```
.pioenvs\thingdev\lib216\libAzureIoTUtility_ID1277.a(time.o): In function `strftime':
time.cpp:(.text.strftime+0x0): multiple definition of `strftime'
C:\users\erikm\.platformio\packages\framework-arduinoespressif8266\tools\sdk\libc\xtensa-lx106-elf\lib\libc.a(lib_a-strftime.o):/Users/igrokhotkov/e/newlib-xtensa/xtensa-lx106-elf/newlib/libc/time/../../../.././newlib/libc/time/strftime.c:695: first defined here
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\thingdev\firmware.elf] Error 1
```

Just compiling this code

```C++
auto clientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString.c_str(), MQTT_Protocol);
```

However if I swap out the AzureIoTProtocol_MQTT with AzureIoTProtocol_HTTP, and the `MQTT_Protocol` for `HTTP_Protocol` compilation works just fine.

**Comment by JetstreamRoySprowl** [comment]
The multiple strftime definition is usually caused by having an out-of-date ESP8266 library. Make sure you've updated to the latest.

**Comment by onionhammer** [comment]
@JetstreamRoySprowl Why not just put it behind an #ifndef ?

**Comment by JetstreamRoySprowl** [comment]
When I last saw this error it was from using an obsolete ESP8266 library. We do not support out-of-date external libraries.

**Comment by rogerdawson** [comment]
I'm getting this same problem. I've downloaded the feather client app [here](https://github.com/Azure-Samples/iot-hub-feather-huzzah-client-app) and it works fine when using Arduino IDE. I've then gone and imported it into platformio and I get the compilation error described above. 

I've run the platformio update but it says everything is up to date so I'm at a bit of a loss.

I'm a bit of a noob to platformio and Arduino IDE so hopefully it's not a stupid question to ask if they use the same libraries? There was a tick box when I did the import stating use Arduino libraries which I didn't select (as it was not recommended) but after I got the error I repeated the import process and checked the use Arduino IDE libraries checkbox and I still get the same error.

**Comment by JetstreamRoySprowl** [comment]
@RogerDawson Hi Roger, I'm afraid platformio is not one of the platforms supported by Microsoft.

**Comment by rogerdawson** [comment]
Oh, that's a shame, VS Code is an infinitely superior IDE to the Arduino one IMHO, you'd think the Microsoft guys would be using that - they do for Edge development. I guess I'll have to stick with the Arduino IDE then, although I can't help but feeling there's a relatively simply fix for this problem. HTTP works fine in platformio, it's just when you try and use the MQTT library things go pear shaped.
