### ISSUE TITLE
Can I use nodemcu instead of Sparkfun or Huzzah

### ISSUE THREAD

**Issue by layaaj** [Azure/azure-iot-arduino-protocol-mqtt#14]
Hi,
I am using nodemcu (Amica version 1.0)  will it support this (azure-iot-arduino-protocol-mqtt
) SDK

**Comment by brendanvanbreda** [comment]
@layaaj it should be compatible since they all run the esp8266, depending on version of ESP you may have memory differences which could cause errors.
