### ISSUE TITLE
Azure IoT hub

### ISSUE THREAD

**Issue by layaaj** [Azure/azure-iot-arduino-protocol-mqtt#15]
Hi,
I am using nodemcu (Amica version 1.0) .I tired to control the device from Iot hub but it didnt work.
i am using arduino ide. In serial monitor this all messages displayed :
                     Connected to wifi
                     Fetching NTP epoch time failed! Waiting 2 seconds to retry.
                     Fetched NTP epoch time is: 1529908191
                     IoTHubClient accepted the message for delivery
                     Message Id: 0 Received.
                    Result Call Back Called! Result is: IOTHUB_CLIENT_CONFIRMATION_OK 
                    pm open,type:2 0 
 
I tried to control the fan ,The backend application is in .NET core .Currently we have added a direct method and checked it with python code by simulating a device through IoT hub. But our need is to make the device simulated by C language and we tried with this code but it didnt hit on  that method. we got the error in the backend application as :
IotHubException: {"Message":"{\"errorCode\":504101,\"trackingId\":\"******************\",\"message\":\"Timed out waiting for the response from device.\",\"info\":{\"timeout\":\"00:00:30\"},\"timestampUtc\":\"*****************\"}","ExceptionMessage":""}   

what is the problem how will i solve it??

Thank you

**Comment by UWBernie** [comment]
I have the same issue, everything works but direct methods

**Comment by jbobotek** [comment]
Try again now
