### ISSUE TITLE
error - MQTT_CLIENT.H missing

### ISSUE THREAD

**Issue by SunilSeth** [Azure/azure-iot-arduino-protocol-mqtt#2]
Am consistently getting compile time error that mqtt_client.h is missing for sample code as well as solution i am trying to run. Please help

**Comment by jorupp** [comment]
I'm hitting the same error too - that file doesn't exist here nor in the directory on my machine the library installed to.  Mentioning @mamokarz to make sure sees this (if he's not watching issues).

**Comment by jorupp** [comment]
Got mine to compile.  I was missing one of the imports in that compilation unit - I didn't realize AzureIoTProtocol_MQTT.h needed the others.

```
#include <AzureIoTHub.h>
#include <AzureIoTUtility.h>
#include <AzureIoTProtocol_MQTT.h>
```

**Comment by mamokarz** [comment]
Hi, sorry about the delay. To use this sample you need in the total three Azure libraries:

Install the AzureIoTHub library via the Arduino IDE Library Manager
Install the AzureIoTUtility library via the Arduino IDE Library Manager
Install the AzureIoTProtocol_MQTT library via the Arduino IDE Library Manager

You are probably missing the AzureIoTHub library.

**Comment by snobu** [comment]
@jorupp, how did you make this work?

```
Build options changed, rebuilding all

In file included from /Users/snobu/Documents/Arduino/azureiothubMQTT/azureiothubMQTT.ino:8:0:
/Users/snobu/Documents/Arduino/libraries/AzureIoTProtocol_MQTT/src/AzureIoTProtocol_MQTT.h:7:39: fatal error: azure_umqtt_c\mqtt_client.h: No such file or directory
 #include "azure_umqtt_c\mqtt_client.h"
                                       ^
compilation terminated.
exit status 1
Error compiling for board Adafruit Feather M0 (Native USB Port).
```

EDIT:

Nevermind, i just dropped this into `AzureIoTProtocol_MQTT.h` and it compiled:
```
#include <AzureIoTHub.h>
#include <AzureIoTUtility.h>
#include <AzureIoTProtocol_MQTT.h>
```

EDIT2:
I'm being silly, i've just created an infinite include loop.

**Comment by jorupp** [comment]
@snobu - I made sure I had all the includes I mentioned in my previous comment included in my .ino file.  I think having them indicates to the Arduino IDE that you want to load those other libraries too, and one of those libraries is what provides the necessary header file.

**Comment by snobu** [comment]
Scratch that. I still can't compile. Same error. I did include the lines at the top of my .ino.

**Comment by jorupp** [comment]
@snobu - do you have have the latest (or at least compatible versions) of all 3 libraries installed via the Arduino IDE Library Manager as @mamokarz mentioned?  Which versions?  Which version of the Arduino IDE?  Which versions of the board libraries?

I'm using:
 - Arduino IDE 1.6.13
 - Adafruit SAMD Boards 1.0.13
 - Arduino SAMD Boards 1.6.11
 - AzureIoTHub 1.0.17
 - AzureIoTProtocol_MQTT 1.0.17
 - AzureIoTUtility 1.0.17

**Comment by snobu** [comment]
Somebody should merge this PR right now: https://github.com/Azure/azure-iot-arduino-protocol-mqtt/pull/5

Just realized i'm on a Mac and backslashes won't work.

**Comment by SunilSeth** [comment]
@jorupp tried to include all three into  .ino but still no luck. Will keep the group posted

**Comment by snobu** [comment]
What error message are you getting? Are you on Windows?

**Comment by tameraw** [comment]
@SunilSeth - we're looking at the PR and will merge ASAP.

**Comment by tameraw** [comment]
PR has been merged. Please let us know if still having issues. Thanks.
