### ISSUE TITLE
are these libs in need of an update?

### ISSUE THREAD

**Issue by lucarv** [Azure/azure-iot-arduino-protocol-mqtt#20]
The simple sample oon mqtt does not compile:

In file included from /Users/lucarv/Documents/Arduino/libraries/AzureIoTUtility/src/azure_c_shared_utility/lock.h:17:0,
                 from /Users/lucarv/Documents/Arduino/libraries/AzureIoTUtility/src/AzureIoTUtility.h:7,
                 from /Users/lucarv/Documents/Arduino/libraries/AzureIoTHub/src/AzureIoTHub.h:7,
                 from sketch/simplesample_mqtt.c:9:
/Users/lucarv/Documents/Arduino/libraries/AzureIoTHub/src/sdk/serializer.h:441:79: error: 'REFLECTED_19' undeclared here (not in a function)
     static const REFLECTED_DATA_FROM_DATAPROVIDER ALL_REFLECTED(name) = { &C2(REFLECTED_, C1(DEC(__COUNTER__))) };
                                                                               ^
/Users/lucarv/Documents/Arduino/libraries/AzureIoTUtility/src/azure_c_shared_utility/macro_utils.h:4359:18: note: in definition of macro 'C2_'
 #define C2_(x,y) x##y
                  ^
/Users/lucarv/Documents/Arduino/libraries/AzureIoTHub/src/sdk/serializer.h:441:76: note: in expansion of macro 'C2'
     static const REFLECTED_DATA_FROM_DATAPROVIDER ALL_REFLECTED(name) = { &C2(REFLECTED_, C1(DEC(__COUNTER__))) };
                                                                            ^
/Users/lucarv/Documents/Arduino/libraries/AzureIoTHub/src/sdk/serializer.h:87:5: note: in expansion of macro 'REFLECTED_LIST_HEAD'
     REFLECTED_LIST_HEAD(schemaNamespace)
     ^
sketch/simplesample_mqtt.c:30:1: note: in expansion of macro 'END_NAMESPACE'
 END_NAMESPACE(WeatherStation);
 ^
exit status 1
Error compiling for board Adafruit Feather HUZZAH ESP8266.

**Comment by jbobotek** [comment]
This lib has since been updated.
