### ISSUE TITLE
Simple MQTT wait for command 

### ISSUE THREAD

**Issue by msuttonricardo** [Azure/azure-iot-arduino-protocol-mqtt#6]
Hi i managed to get the simple MQTT example to work on my MKR1000 by updating the WiFi101 firmware.  as i originally had the same issue a few others on here have had. 

But now i have an issue that the code is waiting for a command. I have poked around and assume that is waiting for one of the 3 actions to execute. ie position, fan on or fan off. I tried to send these as a message from the device explorer but i get a error about decoding a multi tree JSON. Do you know how i trigger the command so that the device will continue onto sending another piece of  data. 

Thanks Matt

**Comment by olivierbloch** [comment]
Hi @msuttonricardo 
The simple sample does the following: It creates a model for the device leveraging the serializer library. this model describes a device that will send 1 telemetry data point (WindSpeed) and will support executing some commands (turn fan on, turn fan off and Set air resistance).
The sample code is such that it will send only one message with the WindSpeed and just wait to receive commands form the Cloud.
The format for the command is detailed in [this documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-serializer#message-handling).
But note that the sample is just a sample and as such the commands won't do much beyond printing some text in the output.
If you want the device to continuously send it's telemetry data, you will have to implement a loop that will execute the piece of code that creates and sends a message to IoT Hub.
Hope this helps
