### ISSUE TITLE
MQTT protocol doesn't deliver user set MessageId or CorrelationId

### ISSUE THREAD

**Issue by GregTerrell** [Azure/azure-iot-arduino-protocol-mqtt#7]
I recently switched our implementation from HTTP to MQTT and noticed an issue regarding system properties.  In our SendMessage() function we set the MessageId and if replying to a command, we set the CorrelationId system properties as shown below.

```
        char messageId[50];
        sprintf(messageId, "%s-%d", deviceId, millis());
        IoTHubMessage_SetMessageId(msgHandle, messageId);
        ...
        if (correlationId != NULL)
        {
          IoTHubMessage_SetCorrelationId(msgHandle, correlationId);
        }
```
During testing of the change I have found that the MQTT protocol is not delivering these two system properties; I am looking at the server side of IoT Hub where these two properties are not present in the SystemProperties dictionary object.  If I switch the protocol to HTTP these system properties are present on the server side of IoT Hub.

Thanks,
Greg

**Comment by mamokarz** [comment]
Hi @GregTerrell ,

In HTTP, the header contains fields for both message-id and correlation-id, but MQTT do not have it. So these two parameters will shows as part of the system properties, with the names `$.mid` and `$.cid`. If you are using the Azure [DeviceExplorer](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer), there is an option in the `Data` to **Show system properties**, set it to find these fields on you message.

Thanks,
Marcos

**Comment by GregTerrell** [comment]
I actually discovered this while trying to troubleshoot an issue with our Azure code.  The messages originating from MQTT devices, when delivered out of IoT Hub (event interface) do not have the MessageId and CorrelationId items in the resulting SystemProperties dictionary.

```
        async Task IEventProcessor.ProcessEventsAsync(PartitionContext context, IEnumerable<EventData> iotHubEvents)
        {
            iotHubPartitionContext = context;

            foreach (EventData iotHubEvent in iotHubEvents)
            {
                checkpointEventCount++;

                if (iotHubEvent.Properties.ContainsKey(EventMessageProperties.IotqiVersion) && ((string)iotHubEvent.Properties[EventMessageProperties.IotqiVersion]).StartsWith(EventMessageProperties.IotqiVersionPrefix))
                {
                    metricsReporter.Metrics.IncomingEvents++;

                    var deviceId = (string)iotHubEvent.SystemProperties["iothub-connection-device-id"];
```
If I set a breakpoint on the last line of the code segment above, the SystemProperties object did not contain either MessageId and CorrelationId like it does for HTTP and AMQP clients.  Further on the Azure side there is no items in the SystemProperties dictionary with a key similar to mid or cid (see VS debug output below).

```
-		Dictionary	Count = 11	System.Collections.Generic.IDictionary<string, object> {System.Collections.Generic.Dictionary<string, object>}
+		[0]	{[x-opt-sequence-number, 245671]}	System.Collections.Generic.KeyValuePair<string, object>
+		[1]	{[x-opt-offset, 17180351936]}	System.Collections.Generic.KeyValuePair<string, object>
+		[2]	{[x-opt-enqueued-time, 5/15/2017 10:09:25 PM]}	System.Collections.Generic.KeyValuePair<string, object>
+		[3]	{[iothub-connection-device-id, cb03e7bb-b2f3-42fa-a272-1c94e2377a26]}	System.Collections.Generic.KeyValuePair<string, object>
+		[4]	{[iothub-connection-auth-method, { "scope": "device", "type": "sas", "issuer": "iothub" }]}	System.Collections.Generic.KeyValuePair<string, object>
+		[5]	{[iothub-connection-auth-generation-id, 636283937403972938]}	System.Collections.Generic.KeyValuePair<string, object>
+		[6]	{[iothub-enqueuedtime, 5/15/2017 10:09:24 PM]}	System.Collections.Generic.KeyValuePair<string, object>
+		[7]	{[iothub-message-source, Telemetry]}	System.Collections.Generic.KeyValuePair<string, object>
+		[8]	{[EnqueuedTimeUtc, 5/15/2017 10:09:25 PM]}	System.Collections.Generic.KeyValuePair<string, object>
+		[9]	{[SequenceNumber, 245671]}	System.Collections.Generic.KeyValuePair<string, object>
+		[10]	{[Offset, 17180351936]}	System.Collections.Generic.KeyValuePair<string, object>

```

**Comment by mamokarz** [comment]
Is your issue on Arduino or C#?

**Comment by GregTerrell** [comment]
This is an Arduino scenario.  

We have been running on HTTP for a couple months (testing) and decided that MQTT is better accepted by our customer base.  During the testing for MQTT this is one of the first things that surface.  If this an Azure issue, I can move to reporting it there.  My company will likely just move the references to messageID and correlation ID to Properties since we already have ~6 proprietary properties there.

**Comment by mamokarz** [comment]
Investigating

**Comment by mamokarz** [comment]
Hi @GregTerrell ,

It is a bug, we are working on it, look for the fix in a few days.

Thanks,
Marcos

**Comment by tameraw** [comment]
@GregTerrell - Fix checked in the main C SDK repo but not released for the kits yet (work in progress to release it)
