### ISSUE TITLE
Sample fails on rapid messages (Error: LmacRxBlk:1)

### ISSUE THREAD

**Issue by kottofy** [Azure/azure-iot-arduino-protocol-mqtt#8]
Sending C2D messages more frequently than ~15 seconds in between causes the sample to only print "LmacRxBlk:1" on the Serial. Is this a problem with using an Adafruit Feather Huzzah (ESP8266) or something with the SDK? 

Edit: Okay, after some digging, I realize this is a problem with the ESP. Is the solution then to buffer the messages being sent to IoT Hub to send one every ~20 seconds or so?

**Comment by JetstreamRoySprowl** [comment]
@kottofy : Hi Kristin, what version of the Azure IoT libraries are you using? A fix for something much like this went through not too long ago, and I'm not sure if it's in the published Arduino libraries yet or not.

**Comment by kottofy** [comment]
@JetstreamRoySprowl Libraries are version 1.0.36. Any insight into those fixes would be much appreciated!

**Comment by JetstreamRoySprowl** [comment]
The change that I believe fixes that has not made it into the published libraries yet. The change is [here](https://github.com/Azure/azure-c-shared-utility/blob/bc5d4eb8f9dbe3092c9cf046db9b7187b5baad4b/adapters/tlsio_arduino.c#L454), and if you drop this tlsio_arduino.c file into your libraries to replace the older version I think that will get you going.

**Comment by JetstreamRoySprowl** [comment]
This fix and all of the latest code is in the 1.0.40 libraries which got pushed yesterday.
